import os
import argparse
from datetime import datetime

def generate_super_doc(vault_path, output_path, extensions=['.md']):
    """
    Concatenates all markdown files in a vault into a single 'Super-Doc' markdown file.
    This solves the 50-source limit of NotebookLM by creating one massive source.
    """
    
    print(f"🚀 Iniciando geração do Super-Doc a partir de: {vault_path}")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = f"# Super-Doc: Meu Segundo Cérebro\n\nGenerated by Gemini 3 Pro Script on {timestamp}\n\n---\n\n"
    
    total_files = 0
    total_chars = 0
    
    try:
        with open(output_path, 'w', encoding='utf-8') as outfile:
            outfile.write(header)
            
            for root, dirs, files in os.walk(vault_path):
                # Ignorar pastas ocultas ou de sistema
                if '.git' in root or '.obsidian' in root or '.trash' in root:
                    continue
                    
                for file in files:
                    if any(file.endswith(ext) for ext in extensions):
                        file_path = os.path.join(root, file)
                        rel_path = os.path.relpath(file_path, vault_path)
                        
                        try:
                            with open(file_path, 'r', encoding='utf-8', errors='ignore') as infile:
                                content = infile.read()
                                
                                # Adicionar metadados do arquivo antes do conteúdo
                                outfile.write(f"\n\n<!-- FILE_START: {rel_path} -->\n")
                                outfile.write(f"# Arquivo: {rel_path}\n\n")
                                outfile.write(content)
                                outfile.write(f"\n\n<!-- FILE_END: {rel_path} -->\n\n")
                                outfile.write("---\n")
                                
                                total_files += 1
                                total_chars += len(content)
                                print(f"✅ Processado: {rel_path}")
                                
                        except Exception as e:
                            print(f"❌ Erro ao ler {rel_path}: {e}")

        print(f"\n✨ Super-Doc gerado com sucesso!")
        print(f"📄 Arquivo: {output_path}")
        print(f"📊 Estatísticas: {total_files} arquivos, {total_chars} caracteres.")
        print(f"💡 Dica: Converta este Markdown para PDF se precisar preservar formatação no NotebookLM.")

    except Exception as e:
        print(f"❌ Erro fatal: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Gera um Super-Doc para NotebookLM a partir de um Vault.')
    parser.add_argument('--vault', required=True, help='Caminho raiz do Vault ou pasta')
    parser.add_argument('--output', required=True, help='Caminho do arquivo de saída (ex: super_doc.md)')
    
    args = parser.parse_args()
    
    generate_super_doc(args.vault, args.output)
