#!/usr/bin/env python3
"""
Handoff Generator for Gemini Delegation
Generates structured instructions for delegating tasks to Gemini.
"""

import argparse
import sys
from datetime import datetime


TASK_TYPES = {
    "processing": "Document Processing",
    "search": "Search and Consolidation",
    "generation": "Massive Generation",
    "refactoring": "Batch Refactoring",
    "audit": "Complete Audit"
}


def generate_handoff(task_type, objectives, files, references, deliverables=None, validations=None):
    """Generate handoff instructions in hybrid format."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    task_name = TASK_TYPES.get(task_type, "Custom Task")

    # Parse objectives
    objectives_list = objectives.split(";") if objectives else []

    # Parse files
    files_list = files.split(",") if files else []

    # Parse references
    references_list = references.split(",") if references else []

    # Parse deliverables
    deliverables_list = deliverables.split(";") if deliverables else []

    # Parse validations
    validations_list = validations.split(";") if validations else []

    # Estimate tokens (rough)
    estimated_tokens = len(files_list) * 15000  # Assume 15k per file average
    estimated_time = max(20, len(files_list) * 3)  # 3 min per file, min 20

    # Generate handoff markdown
    handoff = f"""# DELEGATION TO GEMINI/ANTIGRAVITY

**Date:** {timestamp}
**Task Type:** {task_name}

---

## 🎯 OBJECTIVES

"""

    for i, obj in enumerate(objectives_list, 1):
        handoff += f"{i}. {obj.strip()}\n"

    if not objectives_list:
        handoff += "[Define clear objectives]\n"

    handoff += "\n---\n\n## 📋 DELIVERY CHECKLIST\n\n"

    if deliverables_list:
        for deliv in deliverables_list:
            handoff += f"- [ ] {deliv.strip()}\n"
    else:
        handoff += "- [ ] [Deliverable 1]\n"
        handoff += "- [ ] [Deliverable 2]\n"
        handoff += "- [ ] Update SESSION_LOG.md with work summary\n"

    handoff += "\n---\n\n## 📚 REFERENCES\n\n"

    if references_list:
        handoff += "**Source of truth:**\n"
        for ref in references_list:
            handoff += f"- `{ref.strip()}`\n"
    else:
        handoff += "- Source of truth: [Define primary reference document]\n"

    handoff += "\n**Standards:**\n"
    handoff += "- `00_SISTEMA/PADROES/NOMENCLATURA.md`\n"
    handoff += "- [Add relevant standards]\n"

    handoff += "\n**Templates:**\n"
    handoff += "- [Add relevant templates if applicable]\n"

    handoff += "\n---\n\n## ✅ EXPECTED VALIDATION\n\n"

    if validations_list:
        for val in validations_list:
            handoff += f"- [ ] {val.strip()}\n"
    else:
        handoff += "- [ ] Follow source of truth for all critical values\n"
        handoff += "- [ ] Correct nomenclature (prefixes: RESUMO_, PROJETO_, etc.)\n"
        handoff += "- [ ] Complete frontmatter in all documents\n"
        handoff += "- [ ] Update SESSION_LOG.md\n"

    handoff += "\n---\n\n## 📊 ESTIMATION\n\n"
    handoff += f"- **Files to process:** {len(files_list) if files_list[0] else '[N]'}\n"
    handoff += f"- **Estimated tokens:** ~{estimated_tokens:,}\n"
    handoff += f"- **Estimated time:** {estimated_time} minutes\n"

    handoff += "\n---\n\n## 📁 FILES INVOLVED\n\n"

    if files_list and files_list[0]:
        for file in files_list:
            handoff += f"- `{file.strip()}`\n"
    else:
        handoff += "- [List files to read/modify]\n"

    handoff += "\n---\n\n"
    handoff += "**Generated by:** handoff_generator.py\n"
    handoff += f"**Timestamp:** {timestamp}\n"

    return handoff


def main():
    parser = argparse.ArgumentParser(
        description="Generate handoff instructions for Gemini delegation"
    )
    parser.add_argument(
        "--task-type",
        choices=list(TASK_TYPES.keys()),
        required=True,
        help="Type of task being delegated"
    )
    parser.add_argument(
        "--objectives",
        required=True,
        help="Semicolon-separated list of objectives"
    )
    parser.add_argument(
        "--files",
        default="",
        help="Comma-separated list of files involved"
    )
    parser.add_argument(
        "--references",
        default="",
        help="Comma-separated list of reference documents"
    )
    parser.add_argument(
        "--deliverables",
        default="",
        help="Semicolon-separated list of expected deliverables"
    )
    parser.add_argument(
        "--validations",
        default="",
        help="Semicolon-separated list of validation items"
    )
    parser.add_argument(
        "--output",
        default="HANDOFF.md",
        help="Output file path (default: HANDOFF.md)"
    )

    args = parser.parse_args()

    handoff_content = generate_handoff(
        args.task_type,
        args.objectives,
        args.files,
        args.references,
        args.deliverables,
        args.validations
    )

    # Write to output file
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(handoff_content)

    print(f"✅ Handoff instructions generated: {args.output}")
    print(f"\nPreview:\n")
    print(handoff_content[:500] + "...\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
